### PR TITLE
Parameterized routes accept Unicode letters

### PR DESCRIPTION
**Pull request by marafal**

### CODE REVIEW

**Comment by aisk** [comment]
Cool! I'll think about should this will be supported (probably should), thanks!

**Comment by aisk** [comment]
@marafal Hi, sorry late for reply, I think we should support unicode, but in this PR, the digital characters and dash / low dash is missing, we should fix it before merge, thanks!

**Comment by marafal** [comment]
Hi @aisk.
No problem with the late reply.
Feel free to update as you feel the best.
I did a PR, because, it seems to me a better way than just asking for an evolution.

Best Regards,

**Comment by aisk** [comment]
Merged via #16 with you commit, thanks for contribution!

**Pull request closed without merging**
